### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by micaelillos** [yardnsm/node-mashov#15]
`const mashov = require('node-mashov')`
when this line executes the following error is thrown.
`SyntaxError: Cannot use import statement outside a module
`
Is this project still being maintained ?

**Comment by aniozen** [comment]
כן גם לי אותה בעיה

**Comment by Jelomite** [comment]
I'm not the owner nor a maintainer of the package, but from my observation, this works only with ES6.
#### Solution
 - use ES6.
- transpile the package to ES5.

**Comment by micaelillos** [comment]
I used babel to transpile the package to ES5 didn't seem to help.

**Comment by Jelomite** [comment]
Why not just use es6? Less complicated and is better in the long run.

**Comment by ofekashery** [comment]
Try use ``const mashov = require('node-mashov/dist/node-mashov');``.

**Comment by Jelomite** [comment]
the dist folder works only for the browser. Unless I'm missing something...

**Comment by ofekashery** [comment]
I believe it should work in both browser and Node.js.
The webpack output config should include ``globalObject: 'this'``

**Comment by Jelomite** [comment]
@ofekashery Yet it throws the following error: `ReferenceError: window is not defined`

**UPDATE**:  Using ES6 still doesn't solve the issue, I'm getting the original error @micaelillos described himself.

**Comment by micaelillos** [comment]
Have opened a way simpler and less complicated wrapper.
See: https://github.com/micaelillos/MashovAPI

**Comment by yardnsm** [comment]
As @ofekashery mentioned, the issue was because of a missing `globalObject: 'this'` in webpack's config.

#16 should fix that, Thanks @ofekashery ! 😄
