### ISSUE TITLE
Some functions not binded in client

### ISSUE THREAD

**Issue by santaclaaus213** [yardnsm/node-mashov#4]
I tried doing this: 
```javascript
const express = require('express');
const Mashov = require('node-mashov');

const app = express();

app.get('/user/:year', (request, response) => {
    Mashov.fetchSchools().then(schools => {
        let school = schools.find(s => s.name.includes("my-school-here"));
        let client = new Mashov.Client();
        client.login({
            username: 'myusername',
            password: 'mypass',
            year: request.params.year,
            school
        })
            .then(client.getGrades, (error) => {
                //if sign in failed, it would be here
                response.send("failed to sign in");
            }
        ).then((res) => {
            //code fails here
            client.getAuthDetails();
            //response.send(res);
        });
    });
});
```
I'm getting runtime error `UnhandledPromiseRejectionWarning: TypeError: client.getAuthDetails is not a function`.
The same with setAuthDetails, setStartDate and setEndDate.

**Comment by santaclaaus213** [comment]
@yardnsm I think I already fixed it, I just can't create a pull request. can you add me as a member to this project?

**Comment by yardnsm** [comment]
Thanks for submitting an issue! I'd really prefer that you'll create a PR, as it would be easier for me to review the code. If you still prefer not to, it would be awesome if you explain the fix in here :)

@santaclaaus213

**Comment by santaclaaus213** [comment]
@yardnsm I just had a problem creating a PR, I'm new with github :)
I forked it, proposed a change and created a PR.
