### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by yardnsm** [yardnsm/node-mashov#6]
Also make sure to test these; can be done by creating a TS file and compiling it without errors.

**Comment by ofekashery** [comment]
What do you mean ``TypeScrpt types``?

**Comment by yardnsm** [comment]
Typo :)

Basically it means to add some `.d.ts` file (a declaration file) with all the relevant types. See an example [here](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html).
