### ISSUE TITLE
Accessing JSON API

### ISSUE THREAD

**Issue by Heknon** [yardnsm/node-mashov#9]
Hello, you could say i'm pretty much a beginner in JavaScript, i'm self teaching my self.
I'm currently working on my first big project and I wanted to access the Mashov API and found your wrapper as a result. I couldn't seem to get the wrapper to work so I tried accessing the JSON API by my self.
By looking at your code I found out I can get the list of schools with https://web.mashov.info/api/schools
But I can't seem to see grades, I looked at the code of your API wrapper and concluded that  the link is https://web.mashov.info/api/students/(userId that I got from chrome developer tools - Application - Session storage - mashovStudents-credential)/grades
Console returns with "Failed to load resource: the server responded with a status of 400 ()" upon loading the page, probably some idiotic mistake or misunderstanding.
Hope you could help.

**Comment by ofekashery** [comment]
Do you use this library?

**Comment by Jelomite** [comment]
> I couldn't seem to get the wrapper to work

Please show us what you did so we can help you.
##### Regarding your question - what headers are you supplying when trying to access the API?

**Comment by yardnsm** [comment]
If I got your question right, you're trying to send the request manually.

As the 400 error code may suggest, you request my be malformed in some way. Can you please attach the HTTP request that you've made?

Also notice that this client adds several required cookies 🍪 with authentication data:
https://github.com/yardnsm/node-mashov/blob/master/lib/client.js#L61-L68

You can see the authentication flow in the [login controller](https://github.com/yardnsm/node-mashov/blob/master/lib/controllers/login.js).
